version: "3.9"

services:
  server:
    build: .
    ports:
      - "8001:8000"
    environment:
      ENDPOINT: https://images.codevizon.com
      ENV_TYPE: server
    volumes:
      - ./media:/media
