version: "3.9"

services:
  server:
    build: .
    ports:
      - "8001:8000"
    environment:
      ENDPOINT: https://images.codevizon.com
      MONGO_URL: mongodb+srv://souravlayek:7oIYsm1GfyDCKd30@cluster0.ncxolee.mongodb.net/?retryWrites=true&w=majority
    volumes:
      - ./media:/media
