name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest:arm64

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: linux/arm64
        tags: your-docker-username/your-repo-name:${{ github.sha }}

    # - name: Deploy to Kubernetes
    #   uses: appleboy/kubectl-action@master
    #   with:
    #     args: apply -f deployment.yaml
    #   env:
    #     KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
